### ISSUE TITLE
Set range

### ISSUE THREAD

**Issue by gnato** [JoranBeaufort/Leaflet.idw#5]
In your plugin there is an option to set maximum value. But there is no option to set minimum value. I've read a little about IDW, and if I understood corectly the minimum value is always 0.  But what about situation where I would like to render heatmp from -50 to 0? Is there a quick fix to deal with it?

**Comment by Qinode** [comment]
Hi, gnato. I need this feature recently as well so I forked this project and added an options as displayValue, like the concept in MatLab heatmap. And by default, my fork of the project displays the colour relative to the maximum and the minimum of the data. Maybe you could have a look at it if you still need this feature.

**Comment by spatialsparks** [comment]
Hi there
Cool, thanks a lot for sharing your fork! An easy hack would have been to just add to the values so that the smallest value is 0 for the interpolation (if smallest value is -50, just add 50 and visualise). But the hack seems to be obsolete with Qinodes work, thanks :)
cheers
