### ISSUE TITLE
Set limits on interpolation

### ISSUE THREAD

**Issue by jonasrotilli** [JoranBeaufort/Leaflet.idw#6]
Is it possible to set limits on interpolation?
I have a set of coordinates that form a polygon, and within this polygon there are coordinates with the values. I would like to generate the interpolation only within the poligno and not the whole "world".
Anyone have an idea how to do?

**Comment by jonasrotilli** [comment]
It was answered and solved in the question of the link below:
https://github.com/JoranBeaufort/Leaflet.idw/issues/7

**Comment by spatialsparks** [comment]
Hi there
Perfect, thanks!
Cheers
